package tiku.myapp.com.questions.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import tiku.myapp.com.questions.bean.UserBean;
import tiku.myapp.com.questions.bean.AnswerBean;

import tiku.myapp.com.questions.bean.UserBeanDao;
import tiku.myapp.com.questions.bean.AnswerBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig answerBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final AnswerBeanDao answerBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        answerBeanDaoConfig = daoConfigMap.get(AnswerBeanDao.class).clone();
        answerBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        answerBeanDao = new AnswerBeanDao(answerBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(AnswerBean.class, answerBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        answerBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public AnswerBeanDao getAnswerBeanDao() {
        return answerBeanDao;
    }

}
